name: AUR CI
description: Continuous integration for AUR packages
author: Sergey Kanafyev

branding:
  icon: check-circle
  color: blue

inputs:
  github-token:
    description: GitHub token for creating releases
    required: false
    default: ${{ github.token }}

runs:
  using: docker
  image: ghcr.io/its-me/arch-linux:builder
  entrypoint: entrypoint.sh
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
